name: micron-ai
channels:
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.9
  - cudatoolkit=11.8
  - pip
  - numpy
  - pandas
  - scikit-learn
  - lightgbm=3.3.*
  - xgboost=1.7.*
  - jupyter
  - matplotlib
  - seaborn
  - pyarrow
  - pip:
    - optuna
    - category_encoders
